# Home Assistant Secrets
ha_lat: 0.00000
ha_lng: 0.00000

# Zones
zone_home_lat: 0.00000
zone_home_lng: 0.00000
zone_work_lat: 0.00000
zone_work_lng: 0.00000
zone_parents_lat: 0.00000
zone_parents_lng: 0.00000

# Spotify
spotify_client: FAKE_CLIENT
spotify_secret: FAKE_SECRET

# Telegram
telegram_api_key: FAKE_KEY
telegram_chat_id: FAKE_ID