# Home Assistant Secrets
ha_lat: 0.00000
ha_lng: 0.00000

# Zones
zone_home_lat: 0.00000
zone_home_lng: 0.00000
zone_work_lat: 0.00000
zone_work_lng: 0.00000
zone_parents_lat: 0.00000
zone_parents_lng: 0.00000

# Spotify
spotify_client: FAKE_CLIENT
spotify_secret: FAKE_SECRET
sp_dc: FAKE_SP_DC
sp_key: FAKE_SP_KEY

# Telegram
telegram_api_key: FAKE_KEY
telegram_chat_id: 0

# Darksky
darksky_api_key: FAKE_KEY

# Waze
waze_work_destination: 0.00000, 0.00000
waze_home_destination: 0.00000, 0.00000

# Google
google_client_id: FAKE_ID
google_client_secret: FAKE_SECRET

# Todoist
todoist_api_token: FAKE_TOKEN

# Github
github_api_key: FAKE_API_KEY

# Trakt
trakt_client_id: FAKE_CLIENT_ID
trakt_client_secret: FAKE_CLIENT_SECRET

# Philips tv
philips_tv_username: FAKE_USERNAME
philips_tv_password: FAKE_PASSWORD