title: Settings
icon: mdi:settings
cards:
  - type: entities
    title: States
    show_header_toggle: false
    entities:
      - entity: input_boolean.automatic_home_occupancy
        name: Automatic Home Occupancy Detection
        icon: mdi:home-map-marker
  
  - type: entities
    title: Automations
    show_header_toggle: false
    entities:
      - entity: automation.turn_on_automatic_home_occupancy_detection
        name: '[Telegram callback]Turn on automatic home occupancy detection'
      - entity: automation.send_telegram_message_when_leaving_and_automatic_home_occupancy_detection_is_off
        name: send Telegram message when leaving and automatic home occupancy detection is off
